version: '3.5'
services:
  db:
    container_name: 'db'
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
    ports:
      - '5432:5432'